version: '3.8'

services:

   tomcat-opendjdk8:
      image: ${docker.registry.push.prefix}${docker.image.id}-java8-openjdk:latest
      build:
         context: ./
         dockerfile: Dockerfile-openjdk8

   tomcat-opendjdk11:
      image: ${docker.registry.push.prefix}${docker.image.id}-java11-openjdk:latest
      build:
         context: ./
         dockerfile: Dockerfile-openjdk11

   tomcat-graalvm8:
      image: ${docker.registry.push.prefix}${docker.image.id}-java8-graalvm:latest
      build:
         context: ./
         dockerfile: Dockerfile-graalvm8

   tomcat-graalvm11:
      image: ${docker.registry.push.prefix}${docker.image.id}-java11-graalvm:latest
      build:
         context: ./
         dockerfile: Dockerfile-graalvm11